services:
  db:
    image: postgres:16
    container_name: ai_resume_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ai_resume_matcher
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ai_resume_backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: